name: Simple Action Example
on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: "name to give artifact product"
        default: "artifactsXX"
  push:
      branches:
        - master

jobs:
  BuildAndTest:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: mkdir build
        working-directory: simple_action/
      - name: CMake
        working-directory: simple_action/build
        run: cmake ..
      - name: Build
        working-directory: simple_action/build
        run: make -j `nproc`
      - name: Test
        working-directory: simple_action/build
        run: ./demo

##
## Artifacts
##
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            simple_action/build/demo
          retention-days: 7
